### ISSUE TITLE
Two errors prevent training a ChromBPNet model

### ISSUE THREAD

**Issue by drewmard** [kundajelab/chrombpnet#104]
Hi! I am currently following the tutorial, but ran into errors while training a bias-factorized ChromBPNet model.

I am on the Stanford clusters (Sherlock), and requested a GPU with 64G:

`srun -p gpu -c 4 --gres gpu:1 --time 1-0 --mem=64G --pty bash
`

If I run using docker/singularity, I receive an out of memory error log:

Code:
```
singularity exec --nv -e --no-mount hostfs \
		--bind /oak/stanford/groups/smontgom/amarder/chrombpnet_tutorial/:/mnt \
		docker://kundajelab/chrombpnet:latest chrombpnet pipeline \
		-ibam /mnt/data/downloads/merged.bam \
		-d ATAC \
		-g /mnt/data/downloads/hg38.fa \
		-c /mnt/data/downloads/hg38.chrom.sizes \
		-p /mnt/data/peaks_no_blacklist.bed \
		-n /mnt/data/output_negatives.bed \
		-fl /mnt/data/splits/fold_0.json \
		-b /mnt/bias_model/ENCSR868FGK_bias_fold_0.h5 \
		-o /mnt/chrombpnet_model/ 

```

Output:

![Screen Shot 2023-05-01 at 9 45 36 PM (1)](https://user-images.githubusercontent.com/16930102/235800186-f84d12f7-6314-4005-ab0e-f1b880a171e3.png)

If I create a local installation and install from conda + pypi, then run it, I get the following error log.

Code:

```
chrombpnet pipeline \
        -ibam chrombpnet_tutorial/data/downloads/merged.bam \
        -d "ATAC" \
        -g chrombpnet_tutorial/data/downloads/hg38.fa \
        -c chrombpnet_tutorial/data/downloads/hg38.chrom.sizes \
        -p chrombpnet_tutorial/data/peaks_no_blacklist.bed \
        -n chrombpnet_tutorial/data/output_negatives.bed \
        -fl chrombpnet_tutorial/data/splits/fold_0.json \
        -b chrombpnet_tutorial/bias_model/ENCSR868FGK_bias_fold_0.h5 \
        -o chrombpnet_tutorial/chrombpnet_model/


```
```
Traceback (most recent call last):
  File "/home/users/amarder/micromamba/envs/chrombpnet/bin/chrombpnet", line 8, in <module>
    sys.exit(main())
  File "/home/users/amarder/micromamba/envs/chrombpnet/lib/python3.8/site-packages/chrombpnet/CHROMBPNET.py", line 23, in main
    pipelines.chrombpnet_train_pipeline(args)
  File "/home/users/amarder/micromamba/envs/chrombpnet/lib/python3.8/site-packages/chrombpnet/pipelines.py", line 17, in chrombpnet_train_pipeline
    import chrombpnet.helpers.preprocessing.reads_to_bigwig as reads_to_bigwig
  File "/home/users/amarder/micromamba/envs/chrombpnet/lib/python3.8/site-packages/chrombpnet/helpers/preprocessing/reads_to_bigwig.py", line 8, in <module>
    import chrombpnet.helpers.preprocessing.auto_shift_detect as auto_shift_detect
  File "/home/users/amarder/micromamba/envs/chrombpnet/lib/python3.8/site-packages/chrombpnet/helpers/preprocessing/auto_shift_detect.py", line 11, in <module>
    from modisco.visualization import viz_sequence
  File "/home/users/amarder/micromamba/envs/chrombpnet/lib/python3.8/site-packages/modisco/__init__.py", line 2, in <module>
    from . import aggregator
  File "/home/users/amarder/micromamba/envs/chrombpnet/lib/python3.8/site-packages/modisco/aggregator.py", line 3, in <module>
    from . import affinitymat
  File "/home/users/amarder/micromamba/envs/chrombpnet/lib/python3.8/site-packages/modisco/affinitymat/__init__.py", line 2, in <module>
    from .core import *
  File "/home/users/amarder/micromamba/envs/chrombpnet/lib/python3.8/site-packages/modisco/affinitymat/core.py", line 5, in <module>
    from . import transformers
  File "/home/users/amarder/micromamba/envs/chrombpnet/lib/python3.8/site-packages/modisco/affinitymat/transformers.py", line 11, in <module>
    from ..cluster import phenograph as ph
  File "/home/users/amarder/micromamba/envs/chrombpnet/lib/python3.8/site-packages/modisco/cluster/__init__.py", line 1, in <module>
    from . import core
  File "/home/users/amarder/micromamba/envs/chrombpnet/lib/python3.8/site-packages/modisco/cluster/core.py", line 8, in <module>
    import leidenalg
  File "/home/users/amarder/micromamba/envs/chrombpnet/lib/python3.8/site-packages/leidenalg/__init__.py", line 35, in <module>
    from .functions import ALL_COMMS
  File "/home/users/amarder/micromamba/envs/chrombpnet/lib/python3.8/site-packages/leidenalg/functions.py", line 2, in <module>
    import igraph as _ig
  File "/home/users/amarder/micromamba/envs/chrombpnet/lib/python3.8/site-packages/igraph/__init__.py", line 79, in <module>
    from igraph.clustering import (
  File "/home/users/amarder/micromamba/envs/chrombpnet/lib/python3.8/site-packages/igraph/clustering.py", line 12, in <module>
    from igraph.drawing.colors import ClusterColoringPalette
  File "/home/users/amarder/micromamba/envs/chrombpnet/lib/python3.8/site-packages/igraph/drawing/__init__.py", line 28, in <module>
    from igraph.drawing.graph import DefaultGraphDrawer, MatplotlibGraphDrawer
  File "/home/users/amarder/micromamba/envs/chrombpnet/lib/python3.8/site-packages/igraph/drawing/graph.py", line 27, in <module>
    from igraph.drawing.edge import ArrowEdgeDrawer
  File "/home/users/amarder/micromamba/envs/chrombpnet/lib/python3.8/site-packages/igraph/drawing/edge.py", line 20, in <module>
    cairo = find_cairo()
  File "/home/users/amarder/micromamba/envs/chrombpnet/lib/python3.8/site-packages/igraph/drawing/utils.py", line 438, in find_cairo
    module = __import__(module_name)
  File "/home/users/amarder/micromamba/envs/chrombpnet/lib/python3.8/site-packages/cairocffi/__init__.py", line 47, in <module>
    cairo = dlopen(
  File "/home/users/amarder/micromamba/envs/chrombpnet/lib/python3.8/site-packages/cairocffi/__init__.py", line 44, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "libcairo-2" was found
cannot load library '/home/users/amarder/micromamba/envs/chrombpnet/lib/cairo': /home/users/amarder/micromamba/envs/chrombpnet/lib/cairo: cannot read file data: Is a directory
cannot load library 'libcairo.so.2': libXrender.so.1: cannot open shared object file: No such file or directory
cannot load library 'libcairo.2.dylib': libcairo.2.dylib: cannot open shared object file: No such file or directory
cannot load library 'libcairo-2.dll': libcairo-2.dll: cannot open shared object file: No such file or directory
```

Any help would be appreciated, thank you!

**Comment by panushri25** [comment]
So (1) is still a memory error, try increasing the memory by 40G maybe?

For (2) libcairo is a generic library that comes with most unix systems, but sherlock is very minimal  and you can load the lib cairo package on sherlock using `module load cairo`.  If this is not Sherlock you will have to install the libcairo package yourself or use the provided docker. The docker image should have all the necessary libraries.

**Comment by panushri25** [comment]
I am going to close this repo because of inactivity. Feel free to open it if the issue still persists.
