### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'object'.

### ISSUE THREAD

**Issue by adamklie** [kundajelab/chrombpnet#125]
## Issue
I installed `chrombpnet` from source in a fresh conda instance using the provided installation instructions. After a model finished training successfully, I hit the following error during marginal footprinting:

```bash
/cellar/users/aklie/opt/miniconda3/envs/chrombpnet/lib/python3.8/site-packages/deepdish/io/hdf5io.py:125: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  elif x.dtype == np.object:
Traceback (most recent call last):
  File "/cellar/users/aklie/opt/miniconda3/envs/chrombpnet/bin/chrombpnet", line 33, in <module>
    sys.exit(load_entry_point('chrombpnet', 'console_scripts', 'chrombpnet')())
  File "/cellar/users/aklie/opt/miniconda3/envs/chrombpnet/lib/python3.8/site-packages/chrombpnet/CHROMBPNET.py", line 23, in main
    pipelines.chrombpnet_train_pipeline(args)
  File "/cellar/users/aklie/opt/miniconda3/envs/chrombpnet/lib/python3.8/site-packages/chrombpnet/pipelines.py", line 114, in chrombpnet_train_pipeline
    marginal_footprinting.main(args_copy)
  File "/cellar/users/aklie/opt/miniconda3/envs/chrombpnet/lib/python3.8/site-packages/chrombpnet/evaluation/marginal_footprints/marginal_footprinting.py", line 154, in main
    dd.io.save("{}_footprints.h5".format(args.output_prefix),
  File "/cellar/users/aklie/opt/miniconda3/envs/chrombpnet/lib/python3.8/site-packages/deepdish/io/hdf5io.py", line 584, in save
    _save_level(h5file, group, value, name=key,
  File "/cellar/users/aklie/opt/miniconda3/envs/chrombpnet/lib/python3.8/site-packages/deepdish/io/hdf5io.py", line 234, in _save_level
    _save_level(handler, new_group, entry,
  File "/cellar/users/aklie/opt/miniconda3/envs/chrombpnet/lib/python3.8/site-packages/deepdish/io/hdf5io.py", line 250, in _save_level
    _save_ndarray(handler, group, name, level, filters=filters)
  File "/cellar/users/aklie/opt/miniconda3/envs/chrombpnet/lib/python3.8/site-packages/deepdish/io/hdf5io.py", line 125, in _save_ndarray
    elif x.dtype == np.object:
  File "/cellar/users/aklie/opt/miniconda3/envs/chrombpnet/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

## Environment

```bash
chrombpnet                   0.1.3 (installed from source)
deepdish                     0.3.7
numpy                        1.23.5
```

## Minimal replicated example
```python
import deepdish as dd
import numpy as np
d = {"test": np.array([0,0])}
dd.io.save("test.h5", d, compression='blosc')
```

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cellar/users/aklie/opt/miniconda3/envs/chrombpnet/lib/python3.8/site-packages/deepdish/io/hdf5io.py", line 584, in save
    _save_level(h5file, group, value, name=key,
  File "/cellar/users/aklie/opt/miniconda3/envs/chrombpnet/lib/python3.8/site-packages/deepdish/io/hdf5io.py", line 250, in _save_level
    _save_ndarray(handler, group, name, level, filters=filters)
  File "/cellar/users/aklie/opt/miniconda3/envs/chrombpnet/lib/python3.8/site-packages/deepdish/io/hdf5io.py", line 125, in _save_ndarray
    elif x.dtype == np.object:
  File "/cellar/users/aklie/opt/miniconda3/envs/chrombpnet/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

## Fix
I downgraded `numpy` to `1.23.4` and it seems to fix the problem 🙃 Apparently this is was enforced upon the 1.23.5 release.

**Comment by panushri25** [comment]
Thank you for this @adamklie
