### ISSUE TITLE
Training Bias Model Error

### ISSUE THREAD

**Issue by PetHabib** [kundajelab/chrombpnet#128]
Hi,

i was training the Bias Model and i got the below error, what should i do?

Traceback (most recent call last):
  File "/ix/djishnu/habibp/miniconda/envs/tf_chrombpnet/bin/chrombpnet", line 8, in <module>
    sys.exit(main())
  File "/ix/djishnu/habibp/miniconda/envs/tf_chrombpnet/lib/python3.8/site-packages/chrombpnet/CHROMBPNET.py", line 38, in main
    pipelines.train_bias_pipeline(args)
  File "/ix/djishnu/habibp/miniconda/envs/tf_chrombpnet/lib/python3.8/site-packages/chrombpnet/pipelines.py", line 290, in train_bias_pipeline
    find_bias_hyperparams.main(args_copy)
  File "/ix/djishnu/habibp/miniconda/envs/tf_chrombpnet/lib/python3.8/site-packages/chrombpnet/helpers/hyperparameters/find_bias_hyperparams.py", line 71, in main
    peaks = param_utils.filter_edge_regions(peaks, bw, args.inputlen, peaks_bool=1)
  File "/ix/djishnu/habibp/miniconda/envs/tf_chrombpnet/lib/python3.8/site-packages/chrombpnet/helpers/hyperparameters/param_utils.py", line 29, in filter_edge_regions
    peaks_df = peaks_df[~filtered]
TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by panushri25** [comment]
Can you share your environment details and what are your inputs?

**Comment by PetHabib** [comment]
i am not sure how i can share the envirinment but the inputs are below:


!chrombpnet bias pipeline \
        -ibam /ix/djishnu/habibp/10_ChromBpnet/results/bwa/merged_replicate/IRF4_0h.mRp.clN.sorted.bam \
        -d "ATAC" \
        -g /ix/djishnu/habibp/10_ChromBpnet/hg38.fa \
        -c /ix/djishnu/habibp/10_ChromBpnet/hg38.chrom.sizes \
        -p /ix/djishnu/habibp/10_ChromBpnet/peaks_no_blacklist.bed \
        -n /ix/djishnu/habibp/10_ChromBpnet/output_negatives.bed \
        -fl /ix/djishnu/habibp/10_ChromBpnet/splits/fold_0.json \
        -b 0.5 \
        -o /ix/djishnu/habibp/10_ChromBpnet/bias_model/ \
        -fp GM12878 \
        

and here is the log:


Estimating enzyme shift in input file
Current estimated shift: +0/+0
Making BedGraph
Making Bigwig
non zero bigwig entries in the given chromosome:  4474368
evaluating hyperparameters on the following chromosomes ['chr2', 'chr4', 'chr5', 'chr7', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr21', 'chr22', 'chrX', 'chrY', 'chr8', 'chr20']
Number of non peaks input:  186898
Number of non peaks filtered because the input/output is on the edge:  0
Number of non peaks being used:  186898
Number of non peaks input:  26845
Number of non peaks filtered because the input/output is on the edge:  0
Number of non peaks being used:  26845
