### ISSUE TITLE
chrombpnet pipeline step issue - job getting killed.

### ISSUE THREAD

**Issue by sid5427** [kundajelab/chrombpnet#132]
Hi Anushri,

I am trying to generate chrombpnet models for a group of bams corresponding to cell clusters. My Bias training completed successfully, however the chrombpnet pipeline step fails for all of the clusterwise bams. - here is the log file from one of the runs, same issue everytime.

This is the same conda environment and installation of chrombpnet I have used previously to complete both bias and pipeline training for other projects. The bams were also processed the same way as before i.e. creating capture wise bams, then splitting them according to clusters, and then creating merged bams for each cluster after sorting. Not sure what's going wrong - Only these files are created in the output directory - 

```
auxiliary
-- data_unstranded.bw
evaluation
--bias_metrics.json  
--bias_only_peaks.counts_pearsonr.png  
--bias_only_peaks.profile_jsd.png  
--bias_predictions.h5
--bw_shift_qc.png
logs - empty
models- empty
```

**Server's log file here -** 
```
2023-08-17 21:34:12.121622: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-17 21:34:12.154903: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-17 21:34:12.156381: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-17 21:34:12.158220: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-17 21:34:12.168320: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-17 21:34:12.169837: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-17 21:34:12.171392: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-17 21:34:12.623910: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-17 21:34:12.626233: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-17 21:34:12.627361: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-17 21:34:12.628472: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 78953 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-80GB, pci bus id: 0000:81:00.0, compute capability: 8.0
2023-08-17 21:36:38.621959: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8901
2023-08-17 21:37:47.283848: W tensorflow/core/data/root_dataset.cc:200] Optimization loop failed: CANCELLED: Operation was cancelled
2023-08-17 21:37:49.883046: W tensorflow/core/data/root_dataset.cc:200] Optimization loop failed: CANCELLED: Operation was cancelled
2023-08-17 21:38:33.839135: W tensorflow/core/data/root_dataset.cc:200] Optimization loop failed: CANCELLED: Operation was cancelled
/users/sen2qb/conda_env/chrombpnet_02_10/lib/python3.8/site-packages/scipy/spatial/distance.py:1290: RuntimeWarning: invalid value encountered in divide
  p = p / np.sum(p, axis=axis, keepdims=True)
/users/sen2qb/conda_env/chrombpnet_02_10/lib/python3.8/site-packages/chrombpnet/training/utils/metrics_utils.py:196: RuntimeWarning: invalid value encountered in divide
  profile_prob = profile / np.sum(profile)
/users/sen2qb/conda_env/chrombpnet_02_10/lib/python3.8/site-packages/scipy/spatial/distance.py:1291: RuntimeWarning: invalid value encountered in divide
  q = q / np.sum(q, axis=axis, keepdims=True)
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
/users/sen2qb/.lsbatch/1692321557.684175.shell: line 31: 36154 Killed                  chrombpnet pipeline -ibam sorted_bams/sorted_merged_BMCP.bam -d "ATAC" -g /data/salomonis2/LabFiles/Daud/Genomes/multi_ome/hg38/fasta/genome.fa -c /data/salomonis2/LabFiles/Daud/Genomes/multi_ome/hg38/fasta/sizes_hg38_genome.txt -p peaks_no_blacklist.bed -n nonpeaks/nonpeaks_human_negatives.bed -fl splits/fold_1.json -b all_bias_human_aug_23/models/bias.h5 -o /scratch/sen2qb/human_sep_all_Aug_2023/sorted_merged_BMCP_main/
```
 
Any help figuring out this issue is appreciated.

**Comment by sid5427** [comment]
Hi Anushri,

I solved the previous - an error on my part, didn't allocate enough memory for the job to run. After fixing that the jobs did finish but now I am getting a new error, and as before no files are created - 

Here is the log file - 

```
2023-08-17 23:51:18.466478: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-17 23:51:18.544271: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-17 23:51:18.545926: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-17 23:51:18.549670: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-17 23:51:18.564914: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-17 23:51:18.566525: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-17 23:51:18.568084: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-17 23:51:23.871524: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-17 23:51:23.873254: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-17 23:51:23.874692: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-17 23:51:23.877010: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 78953 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-80GB, pci bus id: 0000:81:00.0, compute capability: 8.0
2023-08-17 23:53:56.788593: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8901
/users/sen2qb/conda_env/chrombpnet_02_10/lib/python3.8/site-packages/scipy/spatial/distance.py:1290: RuntimeWarning: invalid value encountered in divide
  p = p / np.sum(p, axis=axis, keepdims=True)
/users/sen2qb/conda_env/chrombpnet_02_10/lib/python3.8/site-packages/chrombpnet/training/utils/metrics_utils.py:196: RuntimeWarning: invalid value encountered in divide
  profile_prob = profile / np.sum(profile)
/users/sen2qb/conda_env/chrombpnet_02_10/lib/python3.8/site-packages/scipy/spatial/distance.py:1291: RuntimeWarning: invalid value encountered in divide
  q = q / np.sum(q, axis=axis, keepdims=True)
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
Traceback (most recent call last):
  File "/users/sen2qb/conda_env/chrombpnet_02_10/bin/chrombpnet", line 8, in <module>
    sys.exit(main())
  File "/users/sen2qb/conda_env/chrombpnet_02_10/lib/python3.8/site-packages/chrombpnet/CHROMBPNET.py", line 23, in main
    pipelines.chrombpnet_train_pipeline(args)
  File "/users/sen2qb/conda_env/chrombpnet_02_10/lib/python3.8/site-packages/chrombpnet/pipelines.py", line 50, in chrombpnet_train_pipeline
    find_chrombpnet_hyperparams.main(args_copy)
  File "/users/sen2qb/conda_env/chrombpnet_02_10/lib/python3.8/site-packages/chrombpnet/helpers/hyperparameters/find_chrombpnet_hyperparams.py", line 110, in main
    final_cnts = np.concatenate((peak_cnts,np.random.choice(nonpeak_cnts, replace=False, size=(int(args.negative_sampling_ratio*len(peak_cnts))))))
  File "mtrand.pyx", line 965, in numpy.random.mtrand.RandomState.choice
ValueError: Cannot take a larger sample than population when 'replace=False'

```

Any help with this is appreciated!

**Comment by panushri25** [comment]
How many peaks and non peaks do you? How did you get your non peaks?

**Comment by panushri25** [comment]
So the code is trying to sample 0.1*num_peaks of negatives and the number of negatives provided is less than that

**Comment by panushri25** [comment]
Closing this issue because of lack of activity, please feel free to re-open it.

**Comment by sid5427** [comment]
Hi Anushri,

Sorry I was finishing running chrombpnet on my cell cluster wise bams - here is a table which shows the size of the bams, along with the number of peaks and non peaks per cluster - "DNW" stands for did not work. These are the ones which gave me a similar error to as above.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/SEN2QB/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/SEN2QB/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



cluster_name | peaks_no_blacklist | nonpeaks | size | size(mb) | model_Completed | nonpeak_Region > peaks
-- | -- | -- | -- | -- | -- | --
cluster_1 | 559626 | 1788018 | 17G | 17408 | x | YES
cluster_2 | 462449 | 1931321 | 13G | 13312 | x | YES
cluster_3 | 436877 | 1971517 | 13G | 13312 | x | YES
cluster_4 | 549491 | 1791281 | 13G | 13312 | x | YES
cluster_5 | 435132 | 1975956 | 12G | 12288 | x | YES
cluster_6 | 419191 | 2018990 | 12G | 12288 | x | YES
cluster_7 | 429094 | 1990503 | 12G | 12288 | x | YES
cluster_8 | 384568 | 2063044 | 11G | 11264 | x | YES
cluster_9 | 386650 | 2057705 | 9.1G | 9318.4 | x | YES
cluster_10 | 344859 | 2154220 | 8.7G | 8908.8 | x | YES
cluster_11 | 399406 | 2032010 | 8.1G | 8294.4 | x | YES
cluster_12 | 371767 | 2076126 | 6.3G | 6451.2 | x | YES
cluster_13 | 1411660 | 754561 | 6.1G | 6246.4 | dnw | NO
cluster_14 | 1648763 | 618289 | 5.6G | 5734.4 | dnw | NO
cluster_15 | 1674582 | 557572 | 3.1G | 3174.4 | dnw | NO
cluster_16 | 1417792 | 771568 | 2.2G | 2252.8 | dnw | NO
cluster_17 | 891601 | 1209040 | 859M | 859 | dnw | YES
cluster_18 | 702740 | 1456595 | 582M | 582 | dnw | YES
cluster_19 | 128246 | 477104 | 276M | 276 | dnw | YES
cluster_20 | 261103 | 345211 | 229M | 229 | dnw | YES
cluster_21 | 114630 | 462977 | 156M | 156 | dnw | YES
cluster_22 | 101399 | 451619 | 151M | 151 | dnw | YES
cluster_23 | 91991 | 508416 | 114M | 114 | dnw | YES
cluster_24 | 46151 | 638734 | 57M | 57 | x | YES
cluster_25 | 42592 | 663703 | 54M | 54 | x | YES



</body>

</html>

**Comment by panushri25** [comment]
how did you generate the non-peaks for the 4 samples above that are showing this error?

**Comment by panushri25** [comment]
Also how come you have 1 million peaks for these clusters

**Comment by panushri25** [comment]
Also the size you mentioned is of the bams in that cluster correct? And it seems to be the lowest for these files. So my guess is  that these 1 million peaks are not real peaks, and the signal to noise ratio is bad for these samples and is just covering random regions in the genome. Can you check this?

**Comment by kairukuma** [comment]
Hi Anushri, I'm running into the same sample size error. I think the nonpeak size (11011) is way too small compared to the peak size (192602). Here's my log:

```
Bias model pearsonr performance in peaks is: 0.04
{'counts_loss_weight': '1.0', 'filters': '512', 'n_dil_layers': '8', 'bias_model_path': './WT_2_F_BAM_2_bpnet/models/bias_model_scaled.h5', 'inputlen': '2114', 'outputlen': '1000', 'max_jitter': '500', 'chr_fold_path': '/home/kyle/data/mm10/splits/fold_0.json', 'negative_sampling_ratio': '0.1'}
got the model
loading peaks...
got split:train for bed regions:(192602, 10)
loading nonpeaks...
got split:train for bed regions:(11011, 10)
Traceback (most recent call last):
  File "/home/kyle/miniconda3/envs/bpnet/bin/chrombpnet", line 8, in <module>
    sys.exit(main())
  File "/home/kyle/miniconda3/envs/bpnet/lib/python3.8/site-packages/chrombpnet/CHROMBPNET.py", line 23, in main
    pipelines.chrombpnet_train_pipeline(args)
  File "/home/kyle/miniconda3/envs/bpnet/lib/python3.8/site-packages/chrombpnet/pipelines.py", line 73, in chrombpnet_train_pipeline
    train.main(args_copy)
  File "/home/kyle/miniconda3/envs/bpnet/lib/python3.8/site-packages/chrombpnet/training/train.py", line 87, in main
    train_generator = initializers.initialize_generators(args, "train", parameters, return_coords=False)
  File "/home/kyle/miniconda3/envs/bpnet/lib/python3.8/site-packages/chrombpnet/training/data_generators/initializers.py", line 80, in initialize_generators
    generator=batchgen_generator.ChromBPNetBatchGenerator(
  File "/home/kyle/miniconda3/envs/bpnet/lib/python3.8/site-packages/chrombpnet/training/data_generators/batchgen_generator.py", line 51, in __init__
    self.crop_revcomp_data()
  File "/home/kyle/miniconda3/envs/bpnet/lib/python3.8/site-packages/chrombpnet/training/data_generators/batchgen_generator.py", line 68, in crop_revcomp_data
    self.sampled_nonpeak_seqs, self.sampled_nonpeak_cts, self.sampled_nonpeak_coords = subsample_nonpeak_data(self.nonpeak_seqs, self.nonpeak_cts, self.nonpeak_coords, len(self.peak_seqs), self.negative_sampling_ratio)
  File "/home/kyle/miniconda3/envs/bpnet/lib/python3.8/site-packages/chrombpnet/training/data_generators/batchgen_generator.py", line 15, in subsample_nonpeak_data
    nonpeak_indices_to_keep = np.random.choice(len(nonpeak_seqs), size=num_nonpeak_samples, replace=False)
  File "mtrand.pyx", line 965, in numpy.random.mtrand.RandomState.choice
ValueError: Cannot take a larger sample than population when 'replace=False'
```

Based on what you said about the bad signal to noise ratio, is there a way to correct for this or should I decrease the negative sampling ratio (and if so, how do I do it with CLI arguments)? I followed the preprocessing steps including running macs2 with p=0.01 to call peaks. Any advise is greatly appreciated - please let me know what other information you need, thanks!

**Comment by sid5427** [comment]
Hi @kairukuma ,

I am the original poster of this issue, and have pretty much solved this issue on our side. The issue is usually a combination of an incorrect bam or peakset.

How many peaks do you have? and using what macs2 parameters? and how big are your bam files? Could you also post the actual command that you ran for this step?

**Comment by kairukuma** [comment]
Hi Sidharth, thanks for the quick reply.

This error happens when I run on small .bam files of 134M and 237M. I ran chrombpnet previously on a larger 1.7GB .bam file with no issue.

I have 206,774 and 258,544 peaks in these files respectively after removing blacklisted regions. Here's the entire preprocessing script I ran:

```
mkdir $1 && \
samtools sort -@4 ~/data/split_bam_files_20240429/$1.bam -o $1/$1.sorted.bam && \
samtools index $1/$1.sorted.bam && \
macs2 callpeak -t $1/$1.sorted.bam -f BAM -g mm -n $1 -p 0.01 && \
grep '^chr' $1_peaks.narrowPeak > $1/peaks.narrowPeak && \
bedtools slop -i ~/data/mm10/mm10.blacklist.bed.gz -g ~/data/mm10/mm10.chrom.sizes -b 1057 > $1/temp.bed && \
bedtools intersect -v -a $1/peaks.narrowPeak -b $1/temp.bed  > $1/peaks_no_blacklist.bed && \
chrombpnet prep nonpeaks \
-g ~/data/mm10/genome.fa \
-p $1/peaks_no_blacklist.bed \
-c ~/data/mm10/mm10.chrom.sizes \
-fl ~/data/mm10/splits/fold_0.json \
-br ~/data/mm10/mm10.blacklist.bed.gz \
-o $1_output
```

$1 is the first cmd line argument (bam file name) and the `fold_0.json` split file was generated following the preprocessing steps. Here's what it looks like:

```
{
    "test": [
        "chr1",
        "chr3",
        "chr6"
    ],
    "valid": [
        "chr8",
        "chr18"
    ],
    "train": [
        "chr2",
        "chrX",
        "chr4",
        "chr5",
        "chr7",
        "chr10",
        "chr14",
        "chr9",
        "chr11",
        "chr13",
        "chr12",
        "chr15",
        "chr16",
        "chr17",
        "chrY",
        "chr19"
    ]
}
```

I'm currently merging the .bam files together to see if we get enough non peak regions to not trigger the error.

Thanks again for the help!

**Comment by sid5427** [comment]
@kairukuma

I assume you are working on a single cell dataset, with bams created for each cell cluster/group - essentially splitting the main single cell bam into smaller ones?

We found in our testing that bams of sizes 400mb or less, the non peaks generating step does not work. These bams are usually for rare or small cell populations (50 cells or less).

Try with one of your larger cluster's bams - the entire pipeline should run with no issues.
