### ISSUE TITLE
Question on -bm in pred_bw

### ISSUE THREAD

**Issue by zixiaowang17** [kundajelab/chrombpnet#139]
Hi!

I was wondering the argument -bm here should be the self_trained bias model or the bias_model_scaled.h5 in model output:

chrombpnet pred_bw [-h] -bm BIAS_MODEL -cm CHROMBPNET_MODEL -cmb CHROMBPNET_MODEL_NB -r REGIONS -g GENOME -c CHROM_SIZES -op OUT_PREFIX [-b BATCH_SIZE] [-t TQDM]  [-d DEBUG_CHR [DEBUG_CHR ...]]

Appreciate your help!

Zixiao

**Comment by panushri25** [comment]
bias_model_scaled.h5

**Comment by ZixiaoWang17** [comment]
Hi !

Kind of wondering if there is any requirement for the -r regions option in pred_bw process, I tried two bed files while both throw errors:

1. no_black_list.bed file 
```
==================================================================================================
Total params: 6,377,986
Trainable params: 6,377,986
Non-trainable params: 0
__________________________________________________________________________________________________
    chr   start     end                                                  1     2  3         4          5          6  summit
0  chr1   10231   10656 /chrombp/analysis/dat...    35  .   3.16759    5.44620    3.53943     390
1  chr1   41314   41630  /chrombp/analysis/dat...   120  .   5.40353   14.21020   12.01902     117
2  chr1   79031   79628 /chrombp/analysis/dat...   297  .   8.94377   32.22181   29.74627     318
3  chr1  181353  181717 /chrombp/analysis/dat...    67  .   4.09923    8.77305    6.73011     186
4  chr1  778410  779165 /chrombp/analysis/dat...  3749  .  25.60958  379.45306  374.99875     331
Traceback (most recent call last):
  File "/software/env/chrombpnet/bin/chrombpnet", line 8, in <module>
    sys.exit(main())
  File "/software/env/chrombpnet/lib/python3.8/site-packages/chrombpnet/CHROMBPNET.py", line 56, in main
    predict_to_bigwig.main(args)
  File "/software/env/chrombpnet/lib/python3.8/site-packages/chrombpnet/evaluation/make_bigwigs/predict_to_bigwig.py", line 143, in main
    seqs = data_utils.get_seq(regions_df, g, inputlen)
  File "/software/env/chrombpnet/lib/python3.8/site-packages/chrombpnet/training/utils/data_utils.py", line 18, in get_seq
    return one_hot.dna_to_one_hot(vals)
  File "/env/chrombpnet/lib/python3.8/site-packages/chrombpnet/training/utils/one_hot.py", line 19, in dna_to_one_hot
    assert np.all(np.array([len(s) for s in seqs]) == seq_len)
AssertionError
```

2. temp.bed
```
__________________________________________________________________________________________________
    chr     start       end   1   2   3   4   5   6  summit
0  chr1    627846    636161 NaN NaN NaN NaN NaN NaN     NaN
1  chr1   5849030   5851628 NaN NaN NaN NaN NaN NaN     NaN
2  chr1   8908553   8911071 NaN NaN NaN NaN NaN NaN     NaN
3  chr1   9573523   9576054 NaN NaN NaN NaN NaN NaN     NaN
4  chr1  32042766  32045260 NaN NaN NaN NaN NaN NaN     NaN
Traceback (most recent call last):
  File "/software/env/chrombpnet/bin/chrombpnet", line 8, in <module>
    sys.exit(main())
  File "/software/env/chrombpnet/lib/python3.8/site-packages/chrombpnet/CHROMBPNET.py", line 56, in main
    predict_to_bigwig.main(args)
  File "/software/env/chrombpnet/lib/python3.8/site-packages/chrombpnet/evaluation/make_bigwigs/predict_to_bigwig.py", line 136, in main
    regions = bigwig_helper.get_regions(args.regions, outputlen) # output regions
  File "/software/env/chrombpnet/lib/python3.8/site-packages/chrombpnet/evaluation/make_bigwigs/bigwig_helper.py", line 20, in get_regions
    regions = [[x[0], int(x[1])+int(x[9])-seqlen//2, int(x[1])+int(x[9])+seqlen//2, int(x[1])+int(x[9])] for x in regions]
  File "/software/env/chrombpnet/lib/python3.8/site-packages/chrombpnet/evaluation/make_bigwigs/bigwig_helper.py", line 20, in <listcomp>
    regions = [[x[0], int(x[1])+int(x[9])-seqlen//2, int(x[1])+int(x[9])+seqlen//2, int(x[1])+int(x[9])] for x in regions]
IndexError: list index out of range

```

**Comment by zixiaowang17** [comment]
Hi!

I got this error when i used the narrowpeak file from macs2 to train my own dataset, perdicting bigwig file, would you please take a look at that? Thank you so much for your time and help.

The original narrow peak file cannot proceed and has error below, but if i only use the top 1000 rows, it works well

```

Loading LIBD module for samtools/1.17
2023-10-02 15:11:21.882521: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-02 15:11:24.847136: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 30989 MB memory:  -> device: 0, name: Tesla V100S-PCIE-32GB, pci bus id: 0000:3b:00.0, compute capability: 7.0
2023-10-02 15:11:24.849728: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 30989 MB memory:  -> device: 1, name: Tesla V100S-PCIE-32GB, pci bus id: 0000:5e:00.0, compute capability: 7.0
2023-10-02 15:11:24.852162: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 30989 MB memory:  -> device: 2, name: Tesla V100S-PCIE-32GB, pci bus id: 0000:86:00.0, compute capability: 7.0
2023-10-02 15:11:24.854537: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 30989 MB memory:  -> device: 3, name: Tesla V100S-PCIE-32GB, pci bus id: 0000:af:00.0, compute capability: 7.0
Traceback (most recent call last):
  File "/software/env/chrombpnet/bin/chrombpnet", line 8, in <module>
    sys.exit(main())
  File "/software/env/chrombpnet/lib/python3.8/site-packages/chrombpnet/CHROMBPNET.py", line 56, in main
    predict_to_bigwig.main(args)
  File "/software/env/chrombpnet/lib/python3.8/site-packages/chrombpnet/evaluation/make_bigwigs/predict_to_bigwig.py", line 143, in main
    seqs = data_utils.get_seq(regions_df, g, inputlen)
  File "/software/env/chrombpnet/lib/python3.8/site-packages/chrombpnet/training/utils/data_utils.py", line 18, in get_seq
    return one_hot.dna_to_one_hot(vals)
  File "/software/env/chrombpnet/lib/python3.8/site-packages/chrombpnet/training/utils/one_hot.py", line 19, in dna_to_one_hot
    assert np.all(np.array([len(s) for s in seqs]) == seq_len)
AssertionError

```

**Comment by panushri25** [comment]
The reason for this error is documented under NOTE section here https://github.com/kundajelab/chrombpnet/wiki/Generate-prediction-bigwigs

**Comment by zixiaowang17** [comment]
Does it mean that i should somehow throw some peaks at the beginning and the end of chromosone which doesnt satisfy the condition that  "Make sure that regions in the input bed file can be expanded to inputlen (default to 2114)"

**Comment by panushri25** [comment]
Yes, and some of the chromosome contigs are very small and that results in this error.

**Comment by panushri25** [comment]
I have an updated version of the code to handle this, that I will releasee at the end of the week.

**Comment by zixiaowang17** [comment]
Thank you so much for letting me know, appreciate it. Looking forward to the new code! :)

**Comment by zixiaowang17** [comment]
Hi!

I am writing to follow up on the process of the updated version of the code, thanks! :)

**Comment by panushri25** [comment]
Hello @ZixiaoWang17,

I am testing the new release, should be out soon. Will post it here to notify you.

Thank you for your patience.

**Comment by panushri25** [comment]
Hello, 

I updated the code to fix this, can you test this out and let me know?

You can test it out in two ways - 

(1) Install from test pypi. Recommend a new conda environment which should be deleted after using so as to not conflict it with the original pypi release.

`python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ chrombpnet==0.2.23`

(2) Install from GitHub and test the code. The changes are updated in the GitHub repo.

Let me know how this works for you.

Thank you,
Anu

**Comment by zixiaowang17** [comment]
Well received with thanks, I really appreciate your effort and the update!

Will let you the test result ASAP.

Thanks,
Zixiao

**Comment by zixiaowang17** [comment]
Hi!

Thank you so much for the update, I tested one on my side, which went pretty well for me. Sorry for being in late response as that indeed required a lot of computing time.

Additionally, I have a little question on the "-r" argument in pred_bw, the bed file input for prediction, I was wondering which file should I use suppose I want to know a certaion region, say Chr1: pos1- pos2, should I merge this region with the peak file after excluding blacklist, "_negative.bed", or can I make a bed file only including this region, say V1=chr1,V2=pos1,V3=pos2, V4-V10 = NA?

Thank you so much for your time and consideration!

Best,
Zixiao
