### ISSUE TITLE
Error in training chrombpnet model

### ISSUE THREAD

**Issue by zixiaowang17** [kundajelab/chrombpnet#144]
Hi -

Thank you so much for building this!

I got an error 
```
Node: 'functional_1/bpnet_1st_conv/Conv1D'
DNN library is not found.
```
when I run the code here
```
chrombpnet pipeline \
        -ibam xx..bam \
        -d "ATAC" \
        -g hg38.fa \
        -c hg38.chrom.sizes \
        -p peaks_no_blacklist.bed \
        -n negatives.bed \
        -fl splits/fold_0.json \
        -b bias_fold_0.h5 \
        -o chrombpnet_model_bias_ENCODE/ 
```
   
Here is the error log file,

```
Loading LIBD module for samtools/1.17
2023-09-20 00:37:15.365028: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-20 00:37:23.451147: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 146 MB memory:  -> device: 0, name: Tesla V100S-PCIE-32GB, pci bus id: 0000:3b:00.0, compute capability: 7.0
2023-09-20 00:37:23.797531: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 30522 MB memory:  -> device: 1, name: Tesla V100S-PCIE-32GB, pci bus id: 0000:5e:00.0, compute capability: 7.0
2023-09-20 00:37:23.803465: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 30522 MB memory:  -> device: 2, name: Tesla V100S-PCIE-32GB, pci bus id: 0000:86:00.0, compute capability: 7.0
2023-09-20 00:37:23.809035: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 30522 MB memory:  -> device: 3, name: Tesla V100S-PCIE-32GB, pci bus id: 0000:af:00.0, compute capability: 7.0
2023-09-20 00:37:24.132579: I tensorflow/stream_executor/cuda/cuda_driver.cc:739] failed to allocate 146.50M (153616384 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-09-20 00:37:42.139290: W tensorflow/core/common_runtime/bfc_allocator.cc:275] Allocator (GPU_0_bfc) ran out of memory trying to allocate 81.44MiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2023-09-20 00:37:42.139435: W tensorflow/core/kernels/gpu_utils.cc:50] Failed to allocate memory for convolution redzone checking; skipping this check. This is benign and only means that we won't check cudnn for out-of-bounds reads and writes. This message will only be printed once.
2023-09-20 00:37:44.557902: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2023-09-20 00:37:44.611168: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : UNIMPLEMENTED: DNN library is not found.
Traceback (most recent call last):
  File "software/env/chrombpnet/bin/chrombpnet", line 8, in <module>
    sys.exit(main())
  File "software/env/chrombpnet/lib/python3.8/site-packages/chrombpnet/CHROMBPNET.py", line 23, in main
    pipelines.chrombpnet_train_pipeline(args)
  File "software/env/chrombpnet/lib/python3.8/site-packages/chrombpnet/pipelines.py", line 39, in chrombpnet_train_pipeline
    predict.main(args_copy)
  File "software/env/chrombpnet/lib/python3.8/site-packages/chrombpnet/training/predict.py", line 106, in main
    true_counts, profile_probs_predictions, true_counts_sum, counts_sum_predictions, coordinates = predict_on_batch_wrapper(model, test_generator)
  File "software/env/chrombpnet/lib/python3.8/site-packages/chrombpnet/training/predict.py", line 82, in predict_on_batch_wrapper
    preds=model.predict_on_batch(X)
  File "software/env/chrombpnet/lib/python3.8/site-packages/keras/engine/training.py", line 2179, in predict_on_batch
    outputs = self.predict_function(iterator)
  File "software/env/chrombpnet/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "software/env/chrombpnet/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:

Detected at node 'functional_1/bpnet_1st_conv/Conv1D' defined at (most recent call last):
    File "software/env/chrombpnet/bin/chrombpnet", line 8, in <module>
      sys.exit(main())
    File "software/env/chrombpnet/lib/python3.8/site-packages/chrombpnet/CHROMBPNET.py", line 23, in main
      pipelines.chrombpnet_train_pipeline(args)
    File "software/env/chrombpnet/lib/python3.8/site-packages/chrombpnet/pipelines.py", line 39, in chrombpnet_train_pipeline
      predict.main(args_copy)
    File "software/env/chrombpnet/lib/python3.8/site-packages/chrombpnet/training/predict.py", line 106, in main
      true_counts, profile_probs_predictions, true_counts_sum, counts_sum_predictions, coordinates = predict_on_batch_wrapper(model, test_generator)
    File "software/env/chrombpnet/lib/python3.8/site-packages/chrombpnet/training/predict.py", line 82, in predict_on_batch_wrapper
      preds=model.predict_on_batch(X)
    File "software/env/chrombpnet/lib/python3.8/site-packages/keras/engine/training.py", line 2179, in predict_on_batch
      outputs = self.predict_function(iterator)
    File "software/env/chrombpnet/lib/python3.8/site-packages/keras/engine/training.py", line 1801, in predict_function
      return step_function(self, iterator)
    File "software/env/chrombpnet/lib/python3.8/site-packages/keras/engine/training.py", line 1790, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "software/env/chrombpnet/lib/python3.8/site-packages/keras/engine/training.py", line 1783, in run_step
      outputs = model.predict_step(data)
    File "software/env/chrombpnet/lib/python3.8/site-packages/keras/engine/training.py", line 1751, in predict_step
      return self(x, training=False)
    File "software/env/chrombpnet/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "software/env/chrombpnet/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "software/env/chrombpnet/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "software/env/chrombpnet/lib/python3.8/site-packages/keras/engine/functional.py", line 451, in call
      return self._run_internal_graph(
    File "software/env/chrombpnet/lib/python3.8/site-packages/keras/engine/functional.py", line 589, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "software/env/chrombpnet/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "software/env/chrombpnet/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "software/env/chrombpnet/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "software/env/chrombpnet/lib/python3.8/site-packages/keras/layers/convolutional.py", line 248, in call
      outputs = self.convolution_op(inputs, self.kernel)
    File "software/env/chrombpnet/lib/python3.8/site-packages/keras/layers/convolutional.py", line 233, in convolution_op
      return tf.nn.convolution(
Node: 'functional_1/bpnet_1st_conv/Conv1D'
DNN library is not found.
	 [[{{node functional_1/bpnet_1st_conv/Conv1D}}]] [Op:__inference_predict_function_475]
```

**Comment by panushri25** [comment]
One of your first errors seems to be `CUDA_ERROR_OUT_OF_MEMORY: out of memory`

So I think the GPU is not mentioned while running the script (add CUDA_VISIBLE_DEVICES=0 (or any number for free gpu) before the command)

Here it is trying to access all the 4 GPUs on your cluster and one of them seems to have an existing job running and hence is throwing an out of memory error looks like.
