### ISSUE TITLE
Error generating bigwig files in contribution score

### ISSUE THREAD

**Issue by rb56** [kundajelab/chrombpnet#164]
Hi I have the latest version of chrombpnet 0.1.5
and I get this error while running the Generating the bigwig files for the contribution score

```
Traceback (most recent call last):
  File "/chromBPnet/miniconda3/envs/chrombpnet/bin/chrombpnet", line 33, in <module>
    sys.exit(load_entry_point('chrombpnet', 'console_scripts', 'chrombpnet')())
  File "/chromBPnet/chrombpnet/chrombpnet/CHROMBPNET.py", line 68, in main
    importance_hdf5_to_bigwig.main(args_copy)
  File "/chromBPnet/chrombpnet/chrombpnet/evaluation/make_bigwigs/importance_hdf5_to_bigwig.py", line 30, in main
    regions = bigwig_helper.get_regions(args.regions, SEQLEN)
  File "/chromBPnet/chrombpnet/chrombpnet/evaluation/make_bigwigs/bigwig_helper.py", line 41, in get_regions
    regions = [[x[0], int(x[1])+int(x[9])-seqlen//2, int(x[1])+int(x[9])+seqlen//2, int(x[1])+int(x[9])] for x in np.array(regions.values)[regions_used]]
  File "/chromBPnet/chrombpnet/chrombpnet/evaluation/make_bigwigs/bigwig_helper.py", line 41, in <listcomp>
    regions = [[x[0], int(x[1])+int(x[9])-seqlen//2, int(x[1])+int(x[9])+seqlen//2, int(x[1])+int(x[9])] for x in np.array(regions.values)[regions_used]]
TypeError: only size-1 arrays can be converted to Python scalars

```
Has anyone come across this?

**Comment by panushri25** [comment]
Yes similar to #150. Will release a fix for this in a bit.
