### ISSUE TITLE
Error while training ChromBPNet with pre-trained bias model on example dataset

### ISSUE THREAD

**Issue by sadhanagaddam3** [kundajelab/chrombpnet#186]
Hi,

I've been working on setting up the pipeline using example data. but I'm encountering an issue. Below is the error message I'm seeing, can you assist me in fixing this issue?

2024-04-12 15:24:47.046732: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-12 15:25:09.003100: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9777 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:89:00.0, compute capability: 7.5
2024-04-12 15:25:30.458957: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8101
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
WARNING:tensorflow:Callback method `on_train_batch_end` is slow compared to the batch time (batch time: 0.2552s vs `on_train_batch_end` time: 0.4277s). Check your callbacks.
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
WARNING:tensorflow:OMP_NUM_THREADS is no longer used by the default Keras config. To configure the number of threads, use tf.config.threading APIs.
2024-04-13 00:19:34.398663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9777 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:89:00.0, compute capability: 7.5
WARNING:tensorflow:From /python3.9/site-packages/shap/explainers/deep/deep_tf.py:140: The name tf.keras.backend.get_session is deprecated. Please use tf.compat.v1.keras.backend.get_session instead.

Matplotlib is building the font cache; this may take a moment.
Traceback (most recent call last):
  File "/home/.local/bin/modisco", line 128, in <module>
    modiscolite.report.report_motifs(args.h5py, args.output, suffix=args.suffix, 
TypeError: report_motifs() got an unexpected keyword argument 'suffix'
Traceback (most recent call last):
  File "/home/.local/bin/chrombpnet", line 33, in <module>
    sys.exit(load_entry_point('chrombpnet', 'console_scripts', 'chrombpnet')())
  File "/chrombpnet/chrombpnet/CHROMBPNET.py", line 23, in main
    pipelines.chrombpnet_train_pipeline(args)
  File "/chrombpnet/chrombpnet/pipelines.py", line 156, in chrombpnet_train_pipeline
    import chrombpnet.evaluation.modisco.convert_html_to_pdf as convert_html_to_pdf
  File "/chrombpnet/chrombpnet/evaluation/modisco/convert_html_to_pdf.py", line 1, in <module>
    from weasyprint import HTML, CSS
  File "/python3.9/site-packages/weasyprint/__init__.py", line 469, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "/python3.9/site-packages/weasyprint/css/__init__.py", line 27, in <module>
    from . import computed_values, counters, media_queries
  File "/python3.9/site-packages/weasyprint/css/computed_values.py", line 15, in <module>
    from .. import text
  File "/python3.9/site-packages/weasyprint/text.py", line 260, in <module>
    pango = dlopen(ffi, 'pango-1.0', 'libpango-1.0-0', 'libpango-1.0.so.0',
  File "/python3.9/site-packages/weasyprint/text.py", line 255, in dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "/python3.9/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'pango-1.0': pango-1.0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0'

Thanks,
Sadhana

**Comment by panushri25** [comment]
Hello, pango is by default present on most clusters. If you are running this on sherlock you can simply do `module spider pango` to see the pango version availability and load it using `module load`. If this is a different cluster you might have to figure out specific command like this for that cluster. 

Hope this helps, let me know if you have more questions. Thank you!
