### ISSUE TITLE
Error with convert_html_to_pdf

### ISSUE THREAD

**Issue by viramalingam** [kundajelab/chrombpnet#196]
Getting the following error when running both chrombpnet bias-pipeline and chrombpnet pipeline commands on the lab cluster.

```
import chrombpnet.evaluation.modisco.convert_html_to_pdf as convert_html_to_pdf
  File "/users/vir/anaconda3/envs/chrombpnet_new/lib/python3.8/site-packages/chrombpnet/evaluation/modisco/convert_html_to_pdf.py", line 1, in <module>
    from weasyprint import HTML, CSS
  File "/users/vir/anaconda3/envs/chrombpnet_new/lib/python3.8/site-packages/weasyprint/__init__.py", line 469, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "/users/vir/anaconda3/envs/chrombpnet_new/lib/python3.8/site-packages/weasyprint/css/__init__.py", line 27, in <module>
    from . import computed_values, counters, media_queries
  File "/users/vir/anaconda3/envs/chrombpnet_new/lib/python3.8/site-packages/weasyprint/css/computed_values.py", line 15, in <module>
    from .. import text
  File "/users/vir/anaconda3/envs/chrombpnet_new/lib/python3.8/site-packages/weasyprint/text.py", line 258, in <module>
    gobject = dlopen(ffi, 'gobject-2.0', 'libgobject-2.0-0', 'libgobject-2.0.so.0',
  File "/users/vir/anaconda3/envs/chrombpnet_new/lib/python3.8/site-packages/weasyprint/text.py", line 255, in dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "/users/vir/anaconda3/envs/chrombpnet_new/lib/python3.8/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/users/vir/anaconda3/envs/chrombpnet_new/lib/python3.8/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/users/vir/anaconda3/envs/chrombpnet_new/lib/python3.8/site-packages/cffi/api.py", line 828, in _load_backend_lib
    return backend.load_library(path, flags)
OSError: cannot load library 'libgobject-2.0.so.0': /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: ffi_type_uint32, version LIBFFI_BASE_7.0
```

Thanks
Vivek

**Comment by panushri25** [comment]
This seems to be a library issue, did you ask Anna if this is a core library @viramalingam

**Comment by 09oulin** [comment]
Hey, I have recently met a similar problem. How did you solved it? Could you give me some advice on installing the environment?

Traceback (most recent call last):
  File "/home/oulin/.local/bin/chrombpnet", line 33, in <module>
    sys.exit(load_entry_point('chrombpnet', 'console_scripts', 'chrombpnet')())
  File "/home/oulin/chrombpnet/chrombpnet/chrombpnet/CHROMBPNET.py", line 23, in main
    pipelines.chrombpnet_train_pipeline(args)
  File "/home/oulin/chrombpnet/chrombpnet/chrombpnet/pipelines.py", line 156, in chrombpnet_train_pipeline
    import chrombpnet.evaluation.modisco.convert_html_to_pdf as convert_html_to_pdf
  File "/home/oulin/chrombpnet/chrombpnet/chrombpnet/evaluation/modisco/convert_html_to_pdf.py", line 1, in <module>
    from weasyprint import HTML, CSS
  File "/miniconda3/envs/chrombpnetv6/lib/python3.8/site-packages/weasyprint/__init__.py", line 469, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "/miniconda3/envs/chrombpnetv6/lib/python3.8/site-packages/weasyprint/css/__init__.py", line 27, in <module>
    from . import computed_values, counters, media_queries
  File "/miniconda3/envs/chrombpnetv6/lib/python3.8/site-packages/weasyprint/css/computed_values.py", line 15, in <module>
    from .. import text
  File "/miniconda3/envs/chrombpnetv6/lib/python3.8/site-packages/weasyprint/text.py", line 13, in <module>
    import pyphen
  File "/miniconda3/envs/chrombpnetv6/lib/python3.8/site-packages/pyphen/__init__.py", line 32, in <module>
    dictionaries = resources.files('pyphen.dictionaries')
AttributeError: module 'importlib.resources' has no attribute 'files'
