### ISSUE TITLE
Input file shifts inconsistent

### ISSUE THREAD

**Issue by AlGaydosik** [kundajelab/chrombpnet#198]
Hello, 

I have tried to run the chrombpnet model and have gotten this error:

```
Warning: When compiling code please add the following flags to nvcc:
         -gencode arch=compute_35,code=[compute_35,sm_35] \
         -gencode arch=compute_61,code=[compute_61,sm_61] 
         -gencode arch=compute_70,code=[compute_70,sm_70] 
/ihome/pfuschiotti/ams611/.local/lib/python3.8/site-packages/chrombpnet/helpers/preprocessing/auto_shift_detect.py:108: UserWarning: !!! WARNING: Input reads contain chromosomes not in the reference genome fasta provided. Please ensure you are using the correct reference genome. If you are confident you are using the correct reference genome, you can safely ignore this message.
  warnings.warn(colored(msg, 'red'))
Traceback (most recent call last):
  File "/bgfs/pfuschiotti/ams611/envs/chrombpnet/bin/chrombpnet", line 8, in <module>
    sys.exit(main())
  File "/ihome/pfuschiotti/ams611/.local/lib/python3.8/site-packages/chrombpnet/CHROMBPNET.py", line 23, in main
    pipelines.chrombpnet_train_pipeline(args)
  File "/ihome/pfuschiotti/ams611/.local/lib/python3.8/site-packages/chrombpnet/pipelines.py", line 21, in chrombpnet_train_pipeline
    reads_to_bigwig.main(args)
  File "/ihome/pfuschiotti/ams611/.local/lib/python3.8/site-packages/chrombpnet/helpers/preprocessing/reads_to_bigwig.py", line 96, in main
    plus_shift, minus_shift = auto_shift_detect.compute_shift(args.input_bam_file,
  File "/ihome/pfuschiotti/ams611/.local/lib/python3.8/site-packages/chrombpnet/helpers/preprocessing/auto_shift_detect.py", line 232, in compute_shift
    plus_shift, minus_shift = compute_shift_ATAC(ref_plus_pwms, ref_minus_pwms, plus_pwm, minus_pwm)
  File "/ihome/pfuschiotti/ams611/.local/lib/python3.8/site-packages/chrombpnet/helpers/preprocessing/auto_shift_detect.py", line 188, in compute_shift_ATAC
    raise ValueError("Input file shifts inconsistent. Please post an issue")
ValueError: Input file shifts inconsistent. Please post an issue
```

I had this running in an array and the other 4 samples ran perfectly. I split this sample into 2 types of cells from the same original BAM file and the other sample ran fine. My samples are human skin run in snATACseq and have over 1,000 cells per sample. Thank you!

**Comment by panushri25** [comment]
Can you follow the debugging strategies discussed in the following posts and report back? https://github.com/kundajelab/chrombpnet/issues/153, https://github.com/kundajelab/chrombpnet/issues/174 and https://github.com/kundajelab/chrombpnet/issues/176
