### ISSUE TITLE
Nanmean is deprecated, imported, unused, and never tested

### ISSUE THREAD

**Issue by thomas-reimonn** [kundajelab/chrombpnet#201]
In [predict.py](https://github.com/kundajelab/chrombpnet/blob/2bbac2818eeeb902400e83544565a9c546d50257/chrombpnet/training/predict.py#L14) nanmean is imported from scipy. nanmean was deprecated and removed from scipy.stats version 0.18.0: https://stackoverflow.com/questions/40944243/module-scipy-stats-has-no-attribute-nanmean and the version is not pinned in requirements.txt

Additionally, nanmean is never used in `predict.py` so it can just be removed.

There appears to be no testing process that catches this, which prevent the bias pipeline from finishing.

**Comment by tjgibson** [comment]
I have the same issue. When I run `chrombpnet bias pipeline` using the most recent docker image, it fails after training and saving the best model. Here is the error:

```
Traceback (most recent call last):
  File "/opt/conda/bin/chrombpnet", line 33, in <module>
    sys.exit(load_entry_point('chrombpnet', 'console_scripts', 'chrombpnet')())
  File "/scratch/chrombpnet/chrombpnet/CHROMBPNET.py", line 38, in main
    pipelines.train_bias_pipeline(args)
  File "/scratch/chrombpnet/chrombpnet/pipelines.py", line 329, in train_bias_pipeline
    import chrombpnet.training.predict as predict
  File "/scratch/chrombpnet/chrombpnet/training/predict.py", line 14, in <module>
    from scipy import nanmean, nanstd
ImportError: cannot import name 'nanmean' from 'scipy' (/opt/conda/lib/python3.9/site-packages/scipy/__init__.py)
```

**Comment by panushri25** [comment]
fixed in chrombpnet-1.0.1
