### ISSUE TITLE
Variables not expanded with messages printed to terminal and log

### ISSUE THREAD

**Issue by SuhasSrinivasan** [kundajelab/chrombpnet#47]
The following issue was noticed when running `step2*.sh` from the tutorial.

Messages from `src/helpers/preprocessing/bam_to_bigwig.sh` are not being printed as expected.
The variables are not being expanded for printing to console and log.

Example statement from script https://github.com/kundajelab/chrombpnet/blob/135f548ab0f4c3869a40442111b3c09d78bb7a99/src/helpers/preprocessing/bam_to_bigwig.sh#L51

Output:
```
2022-05-30_02-46-43: samtools view -b -@50 data/downloads/merged.bam | bedtools bamtobed -i stdin | awk -v OFS="\t" \'{if ($6=="-"){print $1,$2,$3-4,$4,$5,$6} else if ($6=="+") {print $1,$2+4,$3,$4,$5,$6}}\' | bedtools genomecov -bg -5 -i stdin -g  hg38.chrom.sizes | bedtools sort -i stdin > data/downloads/K562.tmp2
```

**Comment by panushri25** [comment]
Hello Suhas,

thank you for this issue. I am not sure what you mean by expanded. What are you expecting as output here?

**Comment by SuhasSrinivasan** [comment]
> Hello Suhas,
> 
> thank you for this issue. I am not sure what you mean by expanded. What are you expecting as output here?

Thank you, this depends on how the logging was intended to be.
Would it not be easier to interpret the logs if `{print \$1,\$2,\$3-4,\$4,\$5,\$6}` was printed with the values.

Also, there are other minor issues in logging
`echo $( timestamp ): "bedGraphToBigWig $output_prefix.tmp2 $chrom_sizes $output_prefix\_unstranded.bw" | tee -a $logfile`
The `\_` gets printed as is and is not functioning as an escape character for `_`.

**Comment by panushri25** [comment]
Yeah I wasn't thinking of printing all the values for {print \$1,\$2,\$3-4,\$4,\$5,\$6} .. this will print like 100K-200K values from the bed file into the log file and might be redundant? I was initially storing this as an intermediate bed file, but we decided not to have too many intermediate files as it will clutter the directory.  

Thank you for the "\_" print  in the log file. This is already fixed in one of the pull requests.

Thank you for your attention to the details and  the provided feedback :)

**Comment by sroyyors** [comment]
Hi, actually that did not work. I got nan loss and things errored out. Here is the output that I have. Note I did remove the "models" folder and created a new one for tensorflow+gpu.

```
Epoch 00001: val_loss did not improve from inf
Epoch 2/50
2727/2727 [==============================] - 72s 26ms/step - loss: nan - logits_profile_predictions_loss: nan - logcount_predictions_loss: nan - val_loss: nan - val_logits_profile_predictions_loss: nan - val_logcount_predictions_loss: nan

Epoch 00002: val_loss did not improve from inf
Epoch 3/50
2727/2727 [==============================] - 72s 26ms/step - loss: nan - logits_profile_predictions_loss: nan - logcount_predictions_loss: nan - val_loss: nan - val_logits_profile_predictions_loss: nan - val_logcount_predictions_loss: nan

Epoch 00003: val_loss did not improve from inf
Epoch 4/50
2727/2727 [==============================] - 72s 26ms/step - loss: nan - logits_profile_predictions_loss: nan - logcount_predictions_loss: nan - val_loss: nan - val_logits_profile_predictions_loss: nan - val_logcount_predictions_loss: nan

Epoch 00004: val_loss did not improve from inf
Epoch 5/50
2727/2727 [==============================] - 71s 26ms/step - loss: nan - logits_profile_predictions_loss: nan - logcount_predictions_loss: nan - val_loss: nan - val_logits_profile_predictions_loss: nan - val_logcount_predictions_loss: nan
```

and then I get the following errors:

```
Epoch 00005: val_loss did not improve from inf
Restoring model weights from the end of the best epoch.
Traceback (most recent call last):
  File "/mnt/dv/wid/projects7/Roy-singlecell2/sr_work/deeplearning_atac-seq/chrombpnet/src/training/train.py", line 103, in <module>
    main()
  File "/mnt/dv/wid/projects7/Roy-singlecell2/sr_work/deeplearning_atac-seq/chrombpnet/src/training/train.py", line 93, in main
    fit_and_evaluate(model, train_generator, valid_generator, args, architecture_module)
  File "/mnt/dv/wid/projects7/Roy-singlecell2/sr_work/deeplearning_atac-seq/chrombpnet/src/training/train.py", line 43, in fit_and_evaluate
    callbacks=cur_callbacks)
  File "/mnt/ws/home/sroy/old-local-home/.conda/envs/chrombpnet/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1145, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/mnt/ws/home/sroy/old-local-home/.conda/envs/chrombpnet/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 432, in on_epoch_end
    callback.on_epoch_end(epoch, numpy_logs)
  File "/mnt/ws/home/sroy/old-local-home/.conda/envs/chrombpnet/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 1778, in on_epoch_end
    self.model.set_weights(self.best_weights)
  File "/mnt/ws/home/sroy/old-local-home/.conda/envs/chrombpnet/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1852, in set_weights
    if expected_num_weights != len(weights):
TypeError: object of type 'NoneType' has no len()
2022-06-01_00-39-32: python /mnt/dv/wid/projects7/Roy-singlecell2/sr_work/deeplearning_atac-seq/chrombpnet/src/training/predict.py \
        --genome=data/downloads/hg38.fa \
        --bigwig=data/downloads/K562_unstranded.bw \
        --nonpeaks=models/bias_model/filtered.bias_nonpeaks.bed \
        --chr_fold_path=data/splits/fold_0.json \
        --inputlen=2114 \
        --outputlen=1000 \
        --output_prefix=models/bias_model/bias \
        --batch_size=256 \
        --model_h5=models/bias_model/bias.h5
2022-06-01 00:39:33.449133: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/mnt/dv/wid/projects7/Roy-singlecell2/sr_work/deeplearning_atac-seq/chrombpnet/src/training/predict.py", line 173, in <module>
    main()
  File "/mnt/dv/wid/projects7/Roy-singlecell2/sr_work/deeplearning_atac-seq/chrombpnet/src/training/predict.py", line 104, in main
    model=load_model_wrapper(args)
  File "/mnt/dv/wid/projects7/Roy-singlecell2/sr_work/deeplearning_atac-seq/chrombpnet/src/training/predict.py", line 58, in load_model_wrapper
    model=load_model(args.model_h5)
  File "/mnt/ws/home/sroy/old-local-home/.conda/envs/chrombpnet/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 211, in load_model
    loader_impl.parse_saved_model(filepath)
  File "/mnt/ws/home/sroy/old-local-home/.conda/envs/chrombpnet/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 114, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: models/bias_model/bias.h5/{saved_model.pbtxt|saved_model.pb}
"tee -a $logfile" command filed with exit code 0
```

**Comment by SuhasSrinivasan** [comment]
@sroyyors 
Can you try the following TF Example Python script to check what happens
(Again I am not a maintainer, just trying to help as an end user).

```
# TensorFlow Quickstart Advanced
# https://github.com/tensorflow/docs/blob/master/site/en/tutorials/quickstart/advanced.ipynb

import tensorflow as tf
print("TensorFlow version:", tf.__version__)

from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

# Add a channels dimension
x_train = x_train[..., tf.newaxis].astype("float32")
x_test = x_test[..., tf.newaxis].astype("float32")

train_ds = tf.data.Dataset.from_tensor_slices(
    (x_train, y_train)).shuffle(10000).batch(64)

test_ds = tf.data.Dataset.from_tensor_slices((x_test, y_test)).batch(64)

class MyModel(Model):
  def __init__(self):
    super(MyModel, self).__init__()
    self.conv1 = Conv2D(32, 3, activation='relu')
    self.flatten = Flatten()
    self.d1 = Dense(128, activation='relu')
    self.d2 = Dense(10)

  def call(self, x):
    x = self.conv1(x)
    x = self.flatten(x)
    x = self.d1(x)
    return self.d2(x)

# Create an instance of the model

model = MyModel()

loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

optimizer = tf.keras.optimizers.Adam()

train_loss = tf.keras.metrics.Mean(name='train_loss')
train_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(name='train_accuracy')

test_loss = tf.keras.metrics.Mean(name='test_loss')
test_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(name='test_accuracy')

@tf.function
def train_step(images, labels):
  with tf.GradientTape() as tape:
    # training=True is only needed if there are layers with different
    # behavior during training versus inference (e.g. Dropout).
    predictions = model(images, training=True)
    loss = loss_object(labels, predictions)
  gradients = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(gradients, model.trainable_variables))

  train_loss(loss)
  train_accuracy(labels, predictions)

@tf.function
def test_step(images, labels):
  # training=False is only needed if there are layers with different
  # behavior during training versus inference (e.g. Dropout).
  predictions = model(images, training=False)
  t_loss = loss_object(labels, predictions)

  test_loss(t_loss)
  test_accuracy(labels, predictions)

EPOCHS = 5

for epoch in range(EPOCHS):
  # Reset the metrics at the start of the next epoch
  train_loss.reset_states()
  train_accuracy.reset_states()
  test_loss.reset_states()
  test_accuracy.reset_states()

  for images, labels in train_ds:
    train_step(images, labels)

  for test_images, test_labels in test_ds:
    test_step(test_images, test_labels)

  print(
    f'Epoch {epoch + 1}, '
    f'Loss: {train_loss.result()}, '
    f'Accuracy: {train_accuracy.result() * 100}, '
    f'Test Loss: {test_loss.result()}, '
    f'Test Accuracy: {test_accuracy.result() * 100}'
  )

**Comment by sroyyors** [comment]
That worked:
```
Epoch 1, Loss: 2.3026511669158936, Accuracy: 11.181666374206543, Test Loss: 3.409503936767578, Test Accuracy: 10.3100004196167
Epoch 2, Loss: 2.3282878398895264, Accuracy: 11.225000381469727, Test Loss: 2.302363634109497, Test Accuracy: 11.3100004196167
Epoch 3, Loss: 2.3016550540924072, Accuracy: 11.238333702087402, Test Loss: 2.302137613296509, Test Accuracy: 11.369999885559082
Epoch 4, Loss: 2.301574230194092, Accuracy: 11.233333587646484, Test Loss: 2.3016629219055176, Test Accuracy: 11.399999618530273
Epoch 5, Loss: 2.301584482192993, Accuracy: 11.236666679382324, Test Loss: 2.3018643856048584, Test Accuracy: 11.40999984741211
```
