### ISSUE TITLE
tensorflow with GPU support

### ISSUE THREAD

**Issue by sroyyors** [kundajelab/chrombpnet#48]
hi,
I installed everything and am now in the training phase (step 4) however it is quite slow. It seems tensorflow was installed in CPU mode. How should I make tensorflow use the GPU? Here is what my tensorflow package versions.

tensorflow                2.4.1           mkl_py37h2d14ff2_0  
tensorflow-base           2.4.1           mkl_py37h43e0292_0  
tensorflow-estimator      2.6.0              pyh7b7c402_0  
tensorflow-probability    0.12.2             pyhd8ed1ab_1    conda-forge

**Comment by SuhasSrinivasan** [comment]
Hello,

TensorFlow (TF) automatically registers NVIDIA GPUs if the CUDA stack has been setup.
If you are on a linux based OS, try `nvidia-smi` in the terminal.

Also, if you can share the TF initial output, where it is registering devices and loading libraries, it will be easy to identify the issue.

**Comment by sroyyors** [comment]
```

And when I do nvidia-smi I get:

``` Mon May 30 21:12:55 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100 80G...  Off  | 00000000:65:00.0 Off |                    0 |
| N/A   35C    P0    43W / 300W |      2MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100 80G...  Off  | 00000000:CA:00.0 Off |                    0 |
| N/A   35C    P0    43W / 300W |      2MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by SuhasSrinivasan** [comment]
It is good that the drivers and CUDA SDK are recent, and they are working as expected.
TensorFlow usually prints a few lines at the beginning, wonder if it is being suppressed.
Suggest trying the following in Python console.

```
import tensorflow as tf
physical_devices = tf.config.list_physical_devices('CPU')
for dev in physical_devices:
  print(dev)

physical_devices = tf.config.list_physical_devices('GPU')
for dev in physical_devices:
  print(dev)

**Comment by sroyyors** [comment]
print(dev) for CPU gave
`PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')`

but no output for GPU.

Should I install tensorflow-gpu?

**Comment by panushri25** [comment]
Hello @sroyyors,

Were there anything else printed when you ran this code?

```

import tensorflow as tf
physical_devices = tf.config.list_physical_devices('CPU')
for dev in physical_devices:
  print(dev)

physical_devices = tf.config.list_physical_devices('GPU')
for dev in physical_devices:
  print(dev)
```

**Comment by panushri25** [comment]
apart from what you mentioned already I mean. If tensorflow was installed correctly it should say something about trying to work with GPU, but failed because of .....(reasons)... and then saying that it is going to use a cpu

**Comment by sroyyors** [comment]
I installed tensorflow-gpu and it installed some cuda libraries. After that when I do the print dev, I get the following:

```
for dev in physical_devices:
...  print(dev)
... 
PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')
PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')
```

So I think it was that my tensorflow install was defaulting to CPU. 

Now I am doing step4, and I am seeing the following outputs:

```
2022-05-30 23:10:06.143787: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2022-05-30 23:10:06.143809: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2022-05-30 23:10:06.143820: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.10
2022-05-30 23:10:06.143829: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2022-05-30 23:10:06.143839: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2022-05-30 23:10:06.143848: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2022-05-30 23:10:06.143858: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2022-05-30 23:10:06.143868: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2022-05-30 23:10:06.147939: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0, 1
2022-05-30 23:10:06.147972: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
```

I am assuming I will see the messages about the training (epoch..) soon

**Comment by sroyyors** [comment]
ok I think it is working.. I see messages like:

```profile_kernel_size:75
counts_loss_weight:5.8
got the model
loading nonpeaks...
got split:train for bed regions:(174505, 10)
loading nonpeaks...
got split:valid for bed regions:(16068, 10)
Epoch 1/50
``` 

But also seeing these more "diagnostic messages like"
```
2022-05-30 23:28:54.609662: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2022-05-30 23:30:50.797152: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7

```

**Comment by panushri25** [comment]
Yes looks like it is accessing the gpus

**Comment by panushri25** [comment]
if you want to run it on a specific gpu (say gpu 0), you can also just run it as CUDA_VISIBLE_DEVICES=0 bash step6_* instead of just bash step6_*

**Comment by sroyyors** [comment]
Yes I think it is working. I think it might have been that I used conda and not pip. In any case. I will close this comment..now. Thanks for the help.

**Comment by sroyyors** [comment]
Hi,
I am not sure if my message went through, but I am still encountering issues. I seem to be getting nan loss. This actually was not the case for the CPU version. Here is what I see:

```
got split:train for bed regions:(174505, 10)
loading nonpeaks...
got split:valid for bed regions:(16068, 10)
Epoch 1/50
2022-06-01 00:12:00.886512: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2022-06-01 00:13:56.021405: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2022-06-01 00:32:23.702512: W tensorflow/stream_executor/gpu/asm_compiler.cc:63] Running ptxas --version returned 256
2022-06-01 00:32:23.788320: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: ptxas exited with non-zero error code 256, output: 
Relying on driver to perform ptx compilation. 
Modify $PATH to customize ptxas location.
This message will be only logged once.
   5/2727 [..............................] - ETA: 1:11 - loss: 299.8994 - logits_profile_predictions_loss: 212.0670 - logcount_predictions_loss: 15.1435WARNING:tensorflow:Callback method `on_train_batch_end` is slow compared to the batch time (batch time: 0.0072s vs `on_train_batch_end` time: 0.0158s). Check your callbacks.
2727/2727 [==============================] - 1323s 33ms/step - loss: nan - logits_profile_predictions_loss: nan - logcount_predictions_loss: nan - val_loss: nan - val_logits_profile_predictions_loss: nan - val_logcount_predictions_loss: nan

Epoch 00001: val_loss did not improve from inf
Epoch 2/50
2727/2727 [==============================] - 72s 26ms/step - loss: nan - logits_profile_predictions_loss: nan - logcount_predictions_loss: nan - val_loss: nan - val_logits_profile_predictions_loss: nan - val_logcount_predictions_loss: nan

Epoch 00002: val_loss did not improve from inf
Epoch 3/50
2727/2727 [==============================] - 72s 26ms/step - loss: nan - logits_profile_predictions_loss: nan - logcount_predictions_loss: nan - val_loss: nan - val_logits_profile_predictions_loss: nan - val_logcount_predictions_loss: nan

Epoch 00003: val_loss did not improve from inf
Epoch 4/50
2727/2727 [==============================] - 72s 26ms/step - loss: nan - logits_profile_predictions_loss: nan - logcount_predictions_loss: nan - val_loss: nan - val_logits_profile_predictions_loss: nan - val_logcount_predictions_loss: nan

Epoch 00004: val_loss did not improve from inf
Epoch 5/50
2727/2727 [==============================] - 71s 26ms/step - loss: nan - logits_profile_predictions_loss: nan - logcount_predictions_loss: nan - val_loss: nan - val_logits_profile_predictions_loss: nan - val_logcount_predictions_loss: nan

Epoch 00005: val_loss did not improve from inf
Restoring model weights from the end of the best epoch.
```

And after this there are errors:

```
Traceback (most recent call last):
  File "/mnt/dv/wid/projects7/Roy-singlecell2/sr_work/deeplearning_atac-seq/chrombpnet/src/training/train.py", line 103, in <module>
    main()
  File "/mnt/dv/wid/projects7/Roy-singlecell2/sr_work/deeplearning_atac-seq/chrombpnet/src/training/train.py", line 93, in main
    fit_and_evaluate(model, train_generator, valid_generator, args, architecture_module)
  File "/mnt/dv/wid/projects7/Roy-singlecell2/sr_work/deeplearning_atac-seq/chrombpnet/src/training/train.py", line 43, in fit_and_evaluate
    callbacks=cur_callbacks)
  File "/mnt/ws/home/sroy/old-local-home/.conda/envs/chrombpnet/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1145, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/mnt/ws/home/sroy/old-local-home/.conda/envs/chrombpnet/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 432, in on_epoch_end
    callback.on_epoch_end(epoch, numpy_logs)
  File "/mnt/ws/home/sroy/old-local-home/.conda/envs/chrombpnet/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 1778, in on_epoch_end
    self.model.set_weights(self.best_weights)
  File "/mnt/ws/home/sroy/old-local-home/.conda/envs/chrombpnet/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1852, in set_weights
    if expected_num_weights != len(weights):
TypeError: object of type 'NoneType' has no len()
2022-06-01_00-39-32: python /mnt/dv/wid/projects7/Roy-singlecell2/sr_work/deeplearning_atac-seq/chrombpnet/src/training/predict.py \
        --genome=data/downloads/hg38.fa \
        --bigwig=data/downloads/K562_unstranded.bw \
        --nonpeaks=models/bias_model/filtered.bias_nonpeaks.bed \
        --chr_fold_path=data/splits/fold_0.json \
        --inputlen=2114 \
        --outputlen=1000 \
        --output_prefix=models/bias_model/bias \
        --batch_size=256 \
        --model_h5=models/bias_model/bias.h5
2022-06-01 00:39:33.449133: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/mnt/dv/wid/projects7/Roy-singlecell2/sr_work/deeplearning_atac-seq/chrombpnet/src/training/predict.py", line 173, in <module>
    main()
  File "/mnt/dv/wid/projects7/Roy-singlecell2/sr_work/deeplearning_atac-seq/chrombpnet/src/training/predict.py", line 104, in main
    model=load_model_wrapper(args)
  File "/mnt/dv/wid/projects7/Roy-singlecell2/sr_work/deeplearning_atac-seq/chrombpnet/src/training/predict.py", line 58, in load_model_wrapper
    model=load_model(args.model_h5)
  File "/mnt/ws/home/sroy/old-local-home/.conda/envs/chrombpnet/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 211, in load_model
    loader_impl.parse_saved_model(filepath)
  File "/mnt/ws/home/sroy/old-local-home/.conda/envs/chrombpnet/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 114, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: models/bias_model/bias.h5/{saved_model.pbtxt|saved_model.pb}
"tee -a $logfile" command filed with exit code 0
```
I am wondering if I should go back to the tensorflow cpu mode..

**Comment by annashcherbina** [comment]
Hi, please use the requirements.txt here, avoid mixing conda and pip installs also: 

https://github.com/kundajelab/chrombpnet/blob/create-pip-module/requirements.txt

**Comment by panushri25** [comment]
Was there any message before these lines @sroyyors ?

```
got split:train for bed regions:(174505, 10)
loading nonpeaks...
got split:valid for bed regions:(16068, 10)
```

**Comment by panushri25** [comment]
I dont recommend switching back to CPU, training will be very slow.

We will help you figure this out, we can do a zoom call and finish this setup too if we cannot debug it here.

**Comment by sroyyors** [comment]
hi @panushri25, yes, I have the following outputs (last 4 lines repeated for continuity). I get these outputs using the command from step4:

`bash step4_train_bias_model.sh data/downloads/hg38.fa data/downloads/K562_unstranded.bw data/downloads/overlap.bed.gz data/negatives_data/negatives_with_summit.bed data/splits/fold_0.json 0.5 models/bias_model`

```
No logfile supplied - creating one
2022-05-31_23-47-03: python /mnt/dv/wid/projects7/Roy-singlecell2/sr_work/deeplearning_atac-seq/chrombpnet/src/helpers/hyperparameters/find_bias_hyperparams.py \
       --genome=data/downloads/hg38.fa \
       --bigwig=data/downloads/K562_unstranded.bw \
       --peaks=data/downloads/overlap.bed.gz \
       --nonpeaks=data/negatives_data/negatives_with_summit.bed \
       --outlier_threshold=0.99 \
       --chr_fold_path=data/splits/fold_0.json \
       --inputlen=2114 \
       --outputlen=1000 \
       --max_jitter=50 \
       --filters=128 \
       --n_dilation_layers=4 \
       --bias_threshold_factor=0.5 \
       --output_dir models/bias_model
2022-05-31 23:47:06.170729: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
evaluating hyperparameters on the following chromosomes ['chr2', 'chr4', 'chr5', 'chr7', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr21', 'chr22', 'chrX', 'chrY', 'chr8', 'chr20']
Number of non peaks input:  406632
Number of non peaks filtered because the input/output is on the edge:  0
Number of non peaks being used:  406632
Number of non peaks input:  66484
Number of non peaks filtered because the input/output is on the edge:  0
Number of non peaks being used:  66484
Number of peaks input:  203316
Number of peaks filtered because the input/output is on the edge:  0
Number of peaks being used:  203316
Upper bound counts cut-off for bias model training:  102.0
Number of nonpeaks after the upper-bount cut-off:  202270
Number of nonpeaks after applying upper-bound cut-off and removing outliers :  190573
counts_loss_weight: 5.8
2022-05-31_23-53-42: python /mnt/dv/wid/projects7/Roy-singlecell2/sr_work/deeplearning_atac-seq/chrombpnet/src/training/train.py \
       --genome=data/downloads/hg38.fa \
       --bigwig=data/downloads/K562_unstranded.bw \
       --nonpeaks=models/bias_model/filtered.bias_nonpeaks.bed \
       --params=models/bias_model/bias_model_params.tsv \
       --output_prefix=models/bias_model/bias \
       --chr_fold_path=data/splits/fold_0.json \
       --batch_size=64 \
       --architecture_from_file=/mnt/dv/wid/projects7/Roy-singlecell2/sr_work/deeplearning_atac-seq/chrombpnet/src/training/models/bpnet_model.py \
       --trackables logcount_predictions_loss loss logits_profile_predictions_loss val_logcount_predictions_loss val_loss val_logits_profile_predictions_loss
2022-05-31 23:53:43.166601: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2022-05-31 23:53:46.010102: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-05-31 23:53:46.011440: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2022-05-31 23:53:46.060413: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:65:00.0 name: NVIDIA A100 80GB PCIe computeCapability: 8.0
coreClock: 1.41GHz coreCount: 108 deviceMemorySize: 79.17GiB deviceMemoryBandwidth: 1.76TiB/s
2022-05-31 23:53:46.061994: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 1 with properties: 
pciBusID: 0000:ca:00.0 name: NVIDIA A100 80GB PCIe computeCapability: 8.0
coreClock: 1.41GHz coreCount: 108 deviceMemorySize: 79.17GiB deviceMemoryBandwidth: 1.76TiB/s
2022-05-31 23:53:46.062014: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2022-05-31 23:53:46.064266: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2022-05-31 23:53:46.064312: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.10
2022-05-31 23:53:46.066469: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2022-05-31 23:53:46.067003: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2022-05-31 23:53:46.069042: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2022-05-31 23:53:46.070187: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2022-05-31 23:53:46.074122: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2022-05-31 23:53:46.080059: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0, 1
2022-05-31 23:53:46.080385: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-05-31 23:53:46.089346: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-05-31 23:53:46.435934: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:65:00.0 name: NVIDIA A100 80GB PCIe computeCapability: 8.0
coreClock: 1.41GHz coreCount: 108 deviceMemorySize: 79.17GiB deviceMemoryBandwidth: 1.76TiB/s
2022-05-31 23:53:46.437047: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 1 with properties: 
pciBusID: 0000:ca:00.0 name: NVIDIA A100 80GB PCIe computeCapability: 8.0
coreClock: 1.41GHz coreCount: 108 deviceMemorySize: 79.17GiB deviceMemoryBandwidth: 1.76TiB/s
2022-05-31 23:53:46.437074: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2022-05-31 23:53:46.437100: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2022-05-31 23:53:46.437111: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.10
2022-05-31 23:53:46.437121: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2022-05-31 23:53:46.437131: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2022-05-31 23:53:46.437141: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2022-05-31 23:53:46.437151: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2022-05-31 23:53:46.437162: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2022-05-31 23:53:46.440949: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0, 1
2022-05-31 23:53:46.440989: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2022-06-01 00:09:29.334714: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-06-01 00:09:29.334761: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 1 
2022-06-01 00:09:29.334772: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N Y 
2022-06-01 00:09:29.334777: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 1:   Y N 
2022-06-01 00:09:29.339424: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 75673 MB memory) -> physical GPU (device: 0, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:65:00.0, compute capability: 8.0)
2022-06-01 00:09:29.342074: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 75673 MB memory) -> physical GPU (device: 1, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:ca:00.0, compute capability: 8.0)
2022-06-01 00:12:00.034000: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2022-06-01 00:12:00.034633: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2000000000 Hz
WARNING:tensorflow:AutoGraph could not transform <function multinomial_nll at 0x7f7d4dc9fa70> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
{'counts_loss_weight': '5.8', 'filters': '128', 'n_dil_layers': '4', 'inputlen': '2114', 'outputlen': '1000', 'max_jitter': '50', 'chr_fold_path': 'data/splits/fold_0.json', 'negative_sampling_ratio': '1.0'}
params:
filters:128
n_dil_layers:4
conv1_kernel_size:21
profile_kernel_size:75
counts_loss_weight:5.8
got the model
loading nonpeaks...
got split:train for bed regions:(174505, 10)
loading nonpeaks...
got split:valid for bed regions:(16068, 10)
Epoch 1/50

```

**Comment by sroyyors** [comment]
> Hi, please use the requirements.txt here, avoid mixing conda and pip installs also:
> 
> https://github.com/kundajelab/chrombpnet/blob/create-pip-module/requirements.txt

OK will try with my current install one more time.. I avoided pip and conda as much as possible.. but some things just did not install in conda, so I installed pip in conda and installed the tools like tfmodisco.

**Comment by sroyyors** [comment]
Hi,
I tried to install tensorflow-gpu==2.8.0  but our servers don't have the right GLIB version and so this did not work. I have now reinstalled tensorflow==2.4.1 but this is back in CPU mode. The training is slow, but the losses look right. 

Is there a tensorflow-gpu version that you might recommend? Any other suggestions? Our GLIB latest version is GLIBCXX_3.4.19

**Comment by sroyyors** [comment]
hi,
good news. I tried tensorflow-gpu==2.6.0 and that is working!
