### ISSUE TITLE
igraph dependence

### ISSUE THREAD

**Issue by zji90** [kundajelab/chrombpnet#72]
Hi,

when I run step5_interpret_bias_model.sh, I encountered the following error:

ERROR:
Traceback (most recent call last):
  File "/users/zji4/.conda/envs/chrombpnet/lib/python3.8/site-packages/modisco/cluster/run_leiden", line 5, in <module>
    import igraph as ig
ModuleNotFoundError: No module named 'igraph'

Then I tried installing igraph with conda install -y -c igraph within conda, and rerun step5_interpret_bias_model.sh, but a new error occurs:

Traceback (most recent call last):
  File "/users/zji4/.conda/envs/chrombpnet/lib/python3.8/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/users/zji4/.conda/envs/chrombpnet/lib/python3.8/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/users/zji4/.conda/envs/chrombpnet/lib/python3.8/site-packages/pkg_resources/__init__.py", line 800, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (igraph 0.10.0 (/users/zji4/.conda/envs/chrombpnet/lib/python3.8/site-packages), Requirement.parse('igraph<0.10,>=0.9.0'), {'leidenalg'})

**Comment by zji90** [comment]
Hi,

Just checking if this can be fixed? Thanks!

**Comment by annashcherbina** [comment]
Hi @zji90 -- this seems like an issue with the leidenalg dependency. I would recommend the following: 
```
conda activate chrombpnet 
pip uninstall modisco 
(repeat pip uninstall modisco until it says no version found, in case you have multiple versions installed) 
pip uninstall leidenalg 
(again repeat until it says none is found) 
Then: 
pip install modisco==0.5.16.0 
(It should pull in the appropriate leidenalg package with a clean install) 
```
So it might look something like this: 

```
(base) ubuntu@ip-10-14-153-142:~$ conda activate chrombpnet
(chrombpnet) ubuntu@ip-10-14-153-142:~$ pip uninstall modisco
WARNING: Skipping modisco as it is not installed.
(chrombpnet) ubuntu@ip-10-14-153-142:~$ pip uninstall leidenalg
WARNING: Skipping leidenalg as it is not installed.

(chrombpnet) ubuntu@ip-10-14-153-142:~$ pip install modisco==0.5.16.0
Collecting modisco==0.5.16.0
  Using cached modisco-0.5.16.0-py3-none-any.whl
Requirement already satisfied: psutil>=5.4.8 in /opt/anaconda3/envs/chrombpnet/lib/python3.7/site-packages (from modisco==0.5.16.0) (5.9.0)
Collecting joblib>=0.11
  Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 9.6 MB/s eta 0:00:00
Collecting matplotlib>=2.2.5
  Downloading matplotlib-3.5.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.2/11.2 MB 118.2 MB/s eta 0:00:00
Collecting scikit-learn>=0.19
  Using cached scikit_learn-1.0.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (24.8 MB)
Requirement already satisfied: tqdm>=4.38.0 in /opt/anaconda3/envs/chrombpnet/lib/python3.7/site-packages (from modisco==0.5.16.0) (4.64.0)
Collecting h5py>=2.5
  Downloading h5py-3.7.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (4.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.1/4.1 MB 124.2 MB/s eta 0:00:00
Collecting numpy>=1.9
  Downloading numpy-1.21.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 112.8 MB/s eta 0:00:00
Collecting leidenalg>=0.8.7
  Downloading leidenalg-0.8.10-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 97.3 MB/s eta 0:00:00
Collecting igraph<0.10,>=0.9.0
  Downloading igraph-0.9.11-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 128.0 MB/s eta 0:00:00
Collecting fonttools>=4.22.0
  Downloading fonttools-4.37.4-py3-none-any.whl (960 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 960.8/960.8 kB 93.8 MB/s eta 0:00:00
Collecting python-dateutil>=2.7
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/envs/chrombpnet/lib/python3.7/site-packages (from matplotlib>=2.2.5->modisco==0.5.16.0) (21.3)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.4.4-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 93.5 MB/s eta 0:00:00
Requirement already satisfied: pyparsing>=2.2.1 in /opt/anaconda3/envs/chrombpnet/lib/python3.7/site-packages (from matplotlib>=2.2.5->modisco==0.5.16.0) (3.0.9)
Collecting pillow>=6.2.0
  Downloading Pillow-9.2.0-cp37-cp37m-manylinux_2_28_x86_64.whl (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 115.8 MB/s eta 0:00:00
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting scipy>=1.1.0
  Using cached scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
Collecting texttable>=1.6.2
  Using cached texttable-1.6.4-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: typing-extensions in /opt/anaconda3/envs/chrombpnet/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib>=2.2.5->modisco==0.5.16.0) (4.3.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/chrombpnet/lib/python3.7/site-packages (from python-dateutil>=2.7->matplotlib>=2.2.5->modisco==0.5.16.0) (1.16.0)
Installing collected packages: texttable, threadpoolctl, python-dateutil, pillow, numpy, kiwisolver, joblib, igraph, fonttools, cycler, scipy, matplotlib, leidenalg, h5py, scikit-learn, modisco
Successfully installed cycler-0.11.0 fonttools-4.37.4 h5py-3.7.0 igraph-0.9.11 joblib-1.2.0 kiwisolver-1.4.4 leidenalg-0.8.10 matplotlib-3.5.3 modisco-0.5.16.0 numpy-1.21.6 pillow-9.2.0 python-dateutil-2.8.2 scikit-learn-1.0.2 scipy-1.7.3 texttable-1.6.4 threadpoolctl-3.1.0


(chrombpnet) ubuntu@ip-10-14-153-142:~$ pip show leidenalg
Name: leidenalg
Version: 0.8.10
Summary: Leiden is a general algorithm for methods of community detection in large networks.
Home-page: https://github.com/vtraag/leidenalg
Author: V.A. Traag
Author-email: vincent@traag.net
License: GPLv3+
Location: /opt/anaconda3/envs/chrombpnet/lib/python3.7/site-packages
Requires: igraph
Required-by: modisco
```
It should pull in leidenalg 0.8.10, which requires igraph 
You can test the import out: 
```
(chrombpnet) ubuntu@ip-10-14-153-142:~$ python
Python 3.7.13 (default, Mar 29 2022, 02:18:16)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
 >>> import igraph as ig
>>> quit()
```
Let us know if that doesn't fix your issue.

**Comment by zji90** [comment]
Thanks. That fixes the issue of step 5. I don't think I had modisco installed previously. Maybe add that as a dependency?

**Comment by annashcherbina** [comment]
Just to quickly follow up, modisco is in the requirements.txt file (https://github.com/kundajelab/chrombpnet/blob/master/requirements.txt#L18) so it should have been added as a dependency. 

To avoid any other issues, might be good to execute: 
```
pip install -r requirements.txt
```
to make sure you get all the requirements. This should happen already when you are running `pip install -e chrombpnet`, but since modisco was missing from your env, other packages might be too, so can't hurt to run the install command.
